database:
  driver: 'mysql' # mysql, postgresql, sqlite
  host: '127.0.0.1'
  database: 'webstats'
  user: 'root'
  pass: '1234'
events:
  block:
    break: true
    burn: true
    damage: false
    dispense: false
    experience: false
    fade: false
    fromto: false
    grow: false
    ignite: false
    physics: false
    piston: false
    place: true
    redstone: false
    brew: false
    furnace: false
    decay: true
    notes: false
    signs: false
  damage: true
  distance: true
  item:
    break: true
    craft: true
    drop: true
    pickup: true
    use: true
advanced:
  enabled: false
  driver: 'com.mysql.jdbc.Driver'
  url: 'jdbc:mysql://127.0.0.1:3306/webstats?user=root&password=1234'
logging: ''
developer:
  debugging: false
